#!/bin/bash

if [[ -z "${SAVEDIR}" ]] ; then
   SAVEDIR=/vhsave
fi
mkdir -p "$SAVEDIR"

export STEAMAPPID=${STEAMAPPID:-892970}

if [[ -z "${BOX64_LD_LIBRARY_PATH}" ]]; then 
   export BOX64_LD_LIBRARY_PATH="./linux64:/root/steam/linux32"
fi
export BOX64_LOG=${BOX64_LOG:-0}

if [[ -z "${BOX64_TRACE_FILE}" ]]; then
   export BOX64_TRACE_FILE="$SAVEDIR/output.log"
fi
export BOX64_TRACE=${BOX64_TRACE:-0}

# RUN SERVER
export templdpath="${LD_LIBRARY_PATH}"
export LD_LIBRARY_PATH=./linux64:"${LD_LIBRARY_PATH}"
export SteamAppId=${STEAMAPPID}

echo "##############################"
echo "Basic variables running box64:"
echo "BOX64_LD_LIBRARY_PATH: ${BOX64_LD_LIBRARY_PATH}"
echo "BOX64_LOG: ${BOX64_LOG}"
echo "BOX64_TRACE_FILE: ${BOX64_TRACE_FILE}"
echo "BOX64_TRACE: ${BOX64_TRACE}"
echo "##############################"
echo "COMMAND:" box64 ./valheim_server.x86_64 -nographics -batchmode \
  -public "${PUBLIC:-0}" \
  -port "${PORT:-2456}" \
  -name "${NAME:-Docker Valheim}" \
  -world "${WORLD:-Docker}" \
  -savedir "${SAVEDIR}" \
  -password "${PASSWORD:-nopassword}"
echo "##############################"

# Move to the execution folder
cd /root/valheim_server

# Starting the server:
box64 ./valheim_server.x86_64 -nographics -batchmode \
  -public "${PUBLIC:-0}" \
  -port "${PORT:-2456}" \
  -name "${NAME:-Docker Valheim}" \
  -world "${WORLD:-Docker}" \
  -savedir "${SAVEDIR}" \
  -password "${PASSWORD:-nopassword}"

