---
version: "3.7"


services:
  vhserver:
    network_mode: host
    image: "nosklo/varmheim"
    build: 
      context: .
      dockerfile: valheim.Dockerfile
#    environment:
#      NAME: Docker Server
#      WORLD: ServerWorldFilename
#      PASSWORD: nopassword
#      SAVEDIR: /vhsave
#      PUBLIC: 0
#      PORT: 2456
    ports:
      - "2456-2457:2456-2457/udp"
    volumes:
      - "gameserver:/vhsave"

volumes:
  gameserver:
